application: ceconconsultants
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  
- url: /testImages
  static_dir: testImages

- url: /ceConImages
  static_dir: ceConImages
  
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest